---
- name: setup cluster nodes based on ubuntu
  hosts: cluster
  become: true
  roles:
    - common.tools

- name: setup master behavior
  hosts: master
  become: true
  roles:
    - nfs.server
    - k3s.master

- name: setup workers behavior
  hosts: workers
  become: true
  roles:
    - nfs.client
    - k3s.node

- name: setup tshark in cluster
  hosts: cluster
  become: true
  roles:
    - tshark

