---
# tasks file for k3s.master

- name: install and start k3s in master
  shell: 'curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--bind-address={{ hostvars["vm-master"].ansible_host }} --node-external-ip={{ hostvars["vm-master"].ansible_host }} --flannel-iface=eth1" K3S_KUBECONFIG_MODE="644" sh -s -'
  become: true

- name: get server node token
  shell: "cat /var/lib/rancher/k3s/server/node-token"
  become: true
  register: cluster_token

- name: create fact with token
  set_fact:
    cluster_token: "{{ cluster_token }}"

- name: "check directory /etc/rancher/k3s exists"
  stat:
    path: "/etc/rancher/k3s"
  register: etc_rancher_k3s_dir

- name: "create directory /etc/rancher/k3s"
  file:
    path: /etc/rancher/k3s
    state: directory
  become: true
  when: not etc_rancher_k3s_dir.stat.exists

- name: copy private docker registries template configuration
  template:
    src: etc/rancher/k3s/registries.yaml
    dest: /etc/rancher/k3s/registries.yaml
  become: true
  notify: restart k3s service

#  - debug:
#      var: cluster_token.stdout
#
#  - debug:
#      var: hostvars["vm-master"].cluster_token.stdout
#    when: inventory_hostname_short | regex_search('.*master.*')
#
#  - debug:
#      var: hostvars["vm-master"].ansible_host 
#    when: inventory_hostname_short | regex_search('.*master.*')

